In [1]:
import numpy as np

arr = [6, 7, 8, 9]

print(type(arr))

a = np.array(arr)

print(type(a))
print(a.shape)
print(a.dtype)

<class 'list'>
<class 'numpy.ndarray'>
(4,)
int32


In [2]:
print(a.ndim)

b = np.array([[1, 2, 3]])
print(b)

print(b.ndim)
b.shape

1
[[1 2 3]]
2


(1, 3)

In [3]:
arr = [6, 7, 8, 9]

print(type(arr))

<class 'list'>


In [4]:
a=np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)

<class 'numpy.ndarray'>
(4,)
int32


In [5]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
print(b.ndim)
b.shape

2


(2, 3)

In [7]:
np.random.random((2, 3))
np.zeros((2, 3))
np.ones((2, 3))
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
c=np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d=np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

c +d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [9]:
c * d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [10]:
5 / d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [11]:
c ** 2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [16]:
a[0]
a[3]
b[0, 0]
b[1, 2]
c[0, 1]
d[1, 0:2]

array([9., 8.])

In [17]:
e = np.array([[10, 11, 12],[13, 14, 15],
[16, 17, 18],[19, 20, 21]])
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [18]:
e[[2, 0, 3, 1],[2, 1, 0, 2]]
e[e>15] 

array([16, 17, 18, 19, 20, 21])